title: Ryne Smith
description: This sit serves as a way to get to know a but about my background, my interests, and my aspirations.
linkedin_username: ryne-smith
github_username: FarScoutOne
theme: jekyll-theme-cayman